// GENERATED from sheets/chrome.json by tools/gen_table.py -- edit the sheet, never this file.

#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum Slot { FrontalCortex, OperatingSystem, Arms, Hands, Skeleton, NervousSystem, Integumentary, Circulatory, Legs }
#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum Tier { Common, Rare, Epic, Legendary }
#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum Trigger { Passive, KeyOs, KeyArms, KeyInteg, KeyUtil, NotUsable }
#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum Fidelity { Exact, Adapted, NotPossible }
#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum Primitive { StatMod, OnHitProc, Timescale, WeaponMod, SpawnBullet, ProjectileSteer, TargetHack, HudMarkers, Stealth, Heal, Revive, Jump, NotUsed }

pub struct Chrome { pub id: &'static str, pub slot: Slot, pub name: &'static str, pub tiers: &'static [Tier], pub effect: &'static str, pub trigger: Trigger, pub charge: u8, pub cooldown: u8, pub fidelity: Fidelity, pub primitive: Primitive, pub needs_params: bool }

pub const TIER_MULT: &[(Tier, f32)] = &[(Tier::Common, 1.00), (Tier::Rare, 1.25), (Tier::Epic, 1.50), (Tier::Legendary, 1.75)];

pub const CHROME: &[Chrome] = &[
    Chrome { id: "sandevistan", slot: Slot::OperatingSystem, name: "Sandevistan", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "World time to 25% for 6s, you keep full speed", trigger: Trigger::KeyOs, charge: 40, cooldown: 12, fidelity: Fidelity::Exact, primitive: Primitive::Timescale, needs_params: false },
    Chrome { id: "berserk", slot: Slot::OperatingSystem, name: "Berserk", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "+35% damage, +40 poise, -25% damage taken, no stamina drain for 8s", trigger: Trigger::KeyOs, charge: 50, cooldown: 20, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "cyberdeck", slot: Slot::OperatingSystem, name: "Cyberdeck", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Target a hostile, pick one of three hacks: Overturn, Overload, Blind", trigger: Trigger::KeyOs, charge: 30, cooldown: 8, fidelity: Fidelity::Adapted, primitive: Primitive::TargetHack, needs_params: false },
    Chrome { id: "memory_boost", slot: Slot::FrontalCortex, name: "Memory Boost", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+25% runes from kills", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "kiroshi", slot: Slot::FrontalCortex, name: "Kiroshi Optics", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Hostiles within 40m get a marker and an HP readout", trigger: Trigger::KeyUtil, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::HudMarkers, needs_params: false },
    Chrome { id: "limbic", slot: Slot::FrontalCortex, name: "Limbic System Enhancement", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+15% crit chance", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "pain_editor", slot: Slot::FrontalCortex, name: "Pain Editor", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "-30% damage taken below 30% HP", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Exact, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "visual_cortex", slot: Slot::FrontalCortex, name: "Visual Cortex Support", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+25% crit damage", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "self_ice", slot: Slot::FrontalCortex, name: "Self-ICE", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Bleed, frost and poison build up 40% slower", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "gorilla_arms", slot: Slot::Arms, name: "Gorilla Arms", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Unarmed damage x3 and huge poise damage", trigger: Trigger::KeyArms, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::WeaponMod, needs_params: false },
    Chrome { id: "mantis_blades", slot: Slot::Arms, name: "Mantis Blades", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Equipped weapon gains fast bleed and +20% swing speed", trigger: Trigger::KeyArms, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::WeaponMod, needs_params: false },
    Chrome { id: "monowire", slot: Slot::Arms, name: "Monowire", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Equipped weapon gains +60% reach and hits everything in a wide arc", trigger: Trigger::KeyArms, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::WeaponMod, needs_params: false },
    Chrome { id: "projectile_system", slot: Slot::Arms, name: "Projectile Launch System", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Fire a real explosive bolt from your arm", trigger: Trigger::KeyArms, charge: 25, cooldown: 6, fidelity: Fidelity::Adapted, primitive: Primitive::SpawnBullet, needs_params: true },
    Chrome { id: "microgenerator", slot: Slot::Arms, name: "Microgenerator", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Every 5th hit lands a lightning burst", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::OnHitProc, needs_params: false },
    Chrome { id: "microrotors", slot: Slot::Hands, name: "Microrotors", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+15% attack speed", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "smart_link", slot: Slot::Hands, name: "Smart Link", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Ranged shots curve toward the locked target", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::ProjectileSteer, needs_params: false },
    Chrome { id: "titanium_bones", slot: Slot::Skeleton, name: "Titanium Bones", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+25% equip load", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "bionic_lungs", slot: Slot::Skeleton, name: "Bionic Lungs", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+30% stamina and faster recovery", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "dense_marrow", slot: Slot::Skeleton, name: "Dense Marrow", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+20% melee damage", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "feen_x", slot: Slot::Skeleton, name: "Feen-X", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+15% damage absorption", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "kerenzikov", slot: Slot::NervousSystem, name: "Kerenzikov", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "1.5s bullet-time when a dodge-roll starts", trigger: Trigger::Passive, charge: 0, cooldown: 10, fidelity: Fidelity::Exact, primitive: Primitive::Timescale, needs_params: false },
    Chrome { id: "synaptic_accelerator", slot: Slot::NervousSystem, name: "Synaptic Accelerator", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "2s bullet-time when combat starts", trigger: Trigger::Passive, charge: 0, cooldown: 15, fidelity: Fidelity::Exact, primitive: Primitive::Timescale, needs_params: false },
    Chrome { id: "reflex_tuner", slot: Slot::NervousSystem, name: "Reflex Tuner", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "2.5s bullet-time below 25% HP", trigger: Trigger::Passive, charge: 0, cooldown: 25, fidelity: Fidelity::Exact, primitive: Primitive::Timescale, needs_params: false },
    Chrome { id: "neofiber", slot: Slot::NervousSystem, name: "Neofiber", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+20% dodge invincibility", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "nanorelays", slot: Slot::NervousSystem, name: "Nanorelays", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Every bullet-time lasts 50% longer", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Exact, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "subdermal_armor", slot: Slot::Integumentary, name: "Subdermal Armor", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "-20% physical damage taken", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "optical_camo", slot: Slot::Integumentary, name: "Optical Camo", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Enemies lose track of you for 8s", trigger: Trigger::KeyInteg, charge: 40, cooldown: 30, fidelity: Fidelity::Adapted, primitive: Primitive::Stealth, needs_params: false },
    Chrome { id: "cataresist", slot: Slot::Integumentary, name: "Cataresist", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "-30% fire, lightning, holy and magic damage taken", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "grounding_plating", slot: Slot::Integumentary, name: "Grounding Plating", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Immune to lightning stagger, -40% lightning damage", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::StatMod, needs_params: false },
    Chrome { id: "blood_pump", slot: Slot::Circulatory, name: "Blood Pump", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Heal 40% HP on key", trigger: Trigger::KeyInteg, charge: 30, cooldown: 25, fidelity: Fidelity::Exact, primitive: Primitive::Heal, needs_params: false },
    Chrome { id: "biomonitor", slot: Slot::Circulatory, name: "Biomonitor", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Auto-heal 30% HP below 20% HP, once per rest", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Exact, primitive: Primitive::Heal, needs_params: false },
    Chrome { id: "bioconductor", slot: Slot::Circulatory, name: "Bioconductor", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Crits heal 3% HP", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::OnHitProc, needs_params: false },
    Chrome { id: "second_heart", slot: Slot::Circulatory, name: "Second Heart", tiers: &[Tier::Common, Tier::Rare, Tier::Epic, Tier::Legendary], effect: "Revive at 50% HP, once per rest", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Exact, primitive: Primitive::Revive, needs_params: false },
    Chrome { id: "reinforced_tendons", slot: Slot::Legs, name: "Reinforced Tendons", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Jump again in mid-air", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::Jump, needs_params: false },
    Chrome { id: "fortified_ankles", slot: Slot::Legs, name: "Fortified Ankles", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "+40% jump height", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::Jump, needs_params: false },
    Chrome { id: "lynx_paws", slot: Slot::Legs, name: "Lynx Paws", tiers: &[Tier::Common, Tier::Rare, Tier::Epic], effect: "Enemies notice you 50% slower", trigger: Trigger::Passive, charge: 0, cooldown: 0, fidelity: Fidelity::Adapted, primitive: Primitive::Stealth, needs_params: false },
    Chrome { id: "netwatch_netdriver", slot: Slot::OperatingSystem, name: "Netwatch Netdriver", tiers: &[], effect: "Cannot exist here: Elden Ring has no network, cameras or vehicles to hack", trigger: Trigger::NotUsable, charge: 0, cooldown: 0, fidelity: Fidelity::NotPossible, primitive: Primitive::NotUsed, needs_params: false },
];

pub const CHROME_COUNT: usize = 37;
